using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace HackSite.Dto
{
    public class State
    {
        public const string states = "[    { StateName: 'ALABAMA', StateAbbr: 'AL'},    { StateName: 'ALASKA', StateAbbr: 'AK'},    { StateName: 'AMERICAN SAMOA', StateAbbr: 'AS'},    { StateName: 'ARIZONA', StateAbbr: 'AZ'},    { StateName: 'ARKANSAS', StateAbbr: 'AR'},    { StateName: 'CALIFORNIA', StateAbbr: 'CA'},    { StateName: 'COLORADO', StateAbbr: 'CO'},    { StateName: 'CONNECTICUT', StateAbbr: 'CT'},    { StateName: 'DELAWARE', StateAbbr: 'DE'},    { StateName: 'DISTRICT OF COLUMBIA', StateAbbr: 'DC'},    { StateName: 'FEDERATED StateNameS OF MICRONESIA', StateAbbr: 'FM'},    { StateName: 'FLORIDA', StateAbbr: 'FL'},    { StateName: 'GEORGIA', StateAbbr: 'GA'},    { StateName: 'GUAM', StateAbbr: 'GU'},    { StateName: 'HAWAII', StateAbbr: 'HI'},    { StateName: 'IDAHO', StateAbbr: 'ID'},    { StateName: 'ILLINOIS', StateAbbr: 'IL'},    { StateName: 'INDIANA', StateAbbr: 'IN'},    { StateName: 'IOWA', StateAbbr: 'IA'},    { StateName: 'KANSAS', StateAbbr: 'KS'},    { StateName: 'KENTUCKY', StateAbbr: 'KY'},    { StateName: 'LOUISIANA', StateAbbr: 'LA'},    { StateName: 'MAINE', StateAbbr: 'ME'},    { StateName: 'MARSHALL ISLANDS', StateAbbr: 'MH'},    { StateName: 'MARYLAND', StateAbbr: 'MD'},    { StateName: 'MASSACHUSETTS', StateAbbr: 'MA'},    { StateName: 'MICHIGAN', StateAbbr: 'MI'},    { StateName: 'MINNESOTA', StateAbbr: 'MN'},    { StateName: 'MISSISSIPPI', StateAbbr: 'MS'},    { StateName: 'MISSOURI', StateAbbr: 'MO'},    { StateName: 'MONTANA', StateAbbr: 'MT'},    { StateName: 'NEBRASKA', StateAbbr: 'NE'},    { StateName: 'NEVADA', StateAbbr: 'NV'},    { StateName: 'NEW HAMPSHIRE', StateAbbr: 'NH'},    { StateName: 'NEW JERSEY', StateAbbr: 'NJ'},    { StateName: 'NEW MEXICO', StateAbbr: 'NM'},    { StateName: 'NEW YORK', StateAbbr: 'NY'},    { StateName: 'NORTH CAROLINA', StateAbbr: 'NC'},    { StateName: 'NORTH DAKOTA', StateAbbr: 'ND'},    { StateName: 'NORTHERN MARIANA ISLANDS', StateAbbr: 'MP'},    { StateName: 'OHIO', StateAbbr: 'OH'},    { StateName: 'OKLAHOMA', StateAbbr: 'OK'},    { StateName: 'OREGON', StateAbbr: 'OR'},    { StateName: 'PALAU', StateAbbr: 'PW'},    { StateName: 'PENNSYLVANIA', StateAbbr: 'PA'},    { StateName: 'PUERTO RICO', StateAbbr: 'PR'},    { StateName: 'RHODE ISLAND', StateAbbr: 'RI'},    { StateName: 'SOUTH CAROLINA', StateAbbr: 'SC'},    { StateName: 'SOUTH DAKOTA', StateAbbr: 'SD'},    { StateName: 'TENNESSEE', StateAbbr: 'TN'},    { StateName: 'TEXAS', StateAbbr: 'TX'},    { StateName: 'UTAH', StateAbbr: 'UT'},    { StateName: 'VERMONT', StateAbbr: 'VT'},    { StateName: 'VIRGIN ISLANDS', StateAbbr: 'VI'},    { StateName: 'VIRGINIA', StateAbbr: 'VA'},    { StateName: 'WASHINGTON', StateAbbr: 'WA'},    { StateName: 'WEST VIRGINIA', StateAbbr: 'WV'},    { StateName: 'WISCONSIN', StateAbbr: 'WI'},    { StateName: 'WYOMING', StateAbbr: 'WY' }]";
        public string StateName { get; set; }
        public string StateAbbr { get; set; }
    }
}